<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>

        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <MvcBuildViews Condition="'$(Configuration)'=='Debug'">false</MvcBuildViews>
        <MvcBuildViews Condition="'$(Configuration)'=='Release'">true</MvcBuildViews>

        <PreserveCompilationContext>true</PreserveCompilationContext>
        <MvcRazorCompileOnPublish>true</MvcRazorCompileOnPublish>

        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <AnalysisLevel>latest</AnalysisLevel>
        <AnalysisMode>All</AnalysisMode>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <EnablePackageValidation>true</EnablePackageValidation>
        <EnableStrictModeForBaselineValidation>true</EnableStrictModeForBaselineValidation>
        <EnableStrictModeForCompatibleFrameworksInPackage>true</EnableStrictModeForCompatibleFrameworksInPackage>

        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>

        <RepositoryUrl>https://github.com/girlpunk/inventory-sharp.git</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ActualLab.Fusion" Version="14.3.34" />
        <PackageReference Include="AsyncFixer" Version="2.1.0">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="IDisposableAnalyzers" Version="4.0.8">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
        <PackageReference Include="Lindhart.Analyser.MissingAwaitWarning" Version="3.2.0">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Meziantou.Analyzer" Version="3.0.205">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Meziantou.Analyzer.Annotations" Version="1.7.0" />
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.400">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Roslynator.Analyzers" Version="5.0.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Roslynator.CodeFixes" Version="5.0.0">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Roslynator.Formatting.Analyzers" Version="5.0.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <!-- Roslyn generators/analyzers -->
    <ItemGroup>
        <PackageReference Include="ActualLab.Generators" PrivateAssets="all" Version="14.3.34" />
        <PackageReference Include="MemoryPack.Generator" PrivateAssets="all" Version="1.21.4" />
    </ItemGroup>

</Project>
